In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("Smartphone_Usage_And_Addiction_Analysis_Messy.csv")

In [2]:
print(df.shape)

(9030, 16)

In [3]:
df.head()

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,TXN00001,U00001,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,0
1,TXN00002,U00002,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,0
2,TXN00003,U00003,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0
3,TXN00004,U00004,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1
4,TXN00005,U00005,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1

In [4]:
df.dtypes

transaction_id             object
user_id                    object
age                        object
gender                     object
daily_screen_time_hours    object
social_media_hours         object
gaming_hours               object
work_study_hours           object
sleep_hours                object
notifications_per_day      object
app_opens_per_day          object
weekend_screen_time        object
stress_level               object
academic_work_impact       object
addiction_level            object
addicted_label             object
dtype: object

In [5]:
df.isnull().sum()

transaction_id               0
user_id                      0
age                          8
gender                      10
daily_screen_time_hours     13
social_media_hours           8
gaming_hours                10
work_study_hours             3
sleep_hours                  6
notifications_per_day       11
app_opens_per_day           11
weekend_screen_time         14
stress_level                12
academic_work_impact        10
addiction_level            980
addicted_label               0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(160)

In [7]:
df["age"].head(10)

0    21
1    24
2    31
3    32
4    25
5    26
6    25
7    26
8    21
9    35
Name: age, dtype: object

In [8]:
df["age"] = (
    df["age"]
    .astype(str)
    .str.replace("yrs", "", regex=False)
    .str.strip()
)

In [9]:
df["age"] = pd.to_numeric(
    df["age"], errors="coerce"
)

In [10]:
print(df["age"].dtype)
print(df["age"].head(10))

float64
0    21.0
1    24.0
2    31.0
3    32.0
4    25.0
5    26.0
6    25.0
7    26.0
8    21.0
9    35.0
Name: age, dtype: float64

In [12]:
df["age"] = df["age"].astype("Int64")
df["age"].head(10)

0    21
1    24
2    31
3    32
4    25
5    26
6    25
7    26
8    21
9    35
Name: age, dtype: Int64

In [13]:
df["daily_screen_time_hours"].head(10)

0    3.23
1    5.09
2    6.06
3    7.83
4    9.96
5    9.32
6    10.4
7    4.26
8    4.38
9    9.76
Name: daily_screen_time_hours, dtype: object

In [14]:
df["daily_screen_time_hours"] = (
    df["daily_screen_time_hours"]
    .astype(str)
    .str.replace("hrs", "", regex=False)
    .str.strip()
)

In [15]:
df["daily_screen_time_hours"] = pd.to_numeric(
    df["daily_screen_time_hours"],
    errors="coerce"
)

In [16]:
df["daily_screen_time_hours"].head(10)

0     3.23
1     5.09
2     6.06
3     7.83
4     9.96
5     9.32
6    10.40
7     4.26
8     4.38
9     9.76
Name: daily_screen_time_hours, dtype: float64

In [17]:
df["daily_screen_time_hours"].dtype

dtype('float64')

In [20]:
def clean_number(column):
    df[column] = (
        df[column]
        .astype(str)
        .str.replace(",", ".", regex=False)
        .str.replace("hrs", "", regex=False)
        .str.strip()
    )

    df[column] = pd.to_numeric(
        df[column], errors="coerce"
    )

In [21]:
columns = [
    "social_media_hours",
    "gaming_hours",
    "work_study_hours",
    "sleep_hours",
    "notifications_per_day",
    "app_opens_per_day",
    "weekend_screen_time"
]

for column in columns:
    clean_number(column)

In [22]:
df[columns].dtypes

social_media_hours       float64
gaming_hours             float64
work_study_hours         float64
sleep_hours              float64
notifications_per_day    float64
app_opens_per_day        float64
weekend_screen_time      float64
dtype: object

In [23]:
df.isnull().sum()

transaction_id               0
user_id                      0
age                         19
gender                      10
daily_screen_time_hours     21
social_media_hours          13
gaming_hours                21
work_study_hours             7
sleep_hours                  9
notifications_per_day       15
app_opens_per_day           15
weekend_screen_time         18
stress_level                12
academic_work_impact        10
addiction_level            980
addicted_label               0
dtype: int64

In [24]:
df[columns].describe().T

,count,mean,std,min,25%,50%,75%,max
social_media_hours,9017.0,3.282988,1.619582,0.50,1.91,3.27,4.64,15.42
gaming_hours,9009.0,2.030710,1.182929,0.00,1.02,2.05,3.01,13.40
work_study_hours,9023.0,3.263322,1.708962,0.50,1.85,3.25,4.66,25.25
sleep_hours,9021.0,6.748686,1.339755,0.00,5.63,6.74,7.86,20.00
notifications_per_day,9015.0,138.643150,139.959323,20.00,76.50,136.00,191.00,4939.00
app_opens_per_day,9015.0,98.800776,74.786385,15.00,55.00,97.00,140.00,2986.00
weekend_screen_time,9012.0,9.308075,2.950740,3.58,7.00,9.29,11.55,47.90

In [25]:
df["age"].describe()

count       9011.0
mean     26.636333
std       6.625174
min            0.0
25%           22.0
50%           27.0
75%           31.0
max          250.0
Name: age, dtype: Float64

In [26]:
df.loc[
    (df["age"] < 13) | (df["age"] > 100),
    ["user_id", "age"]
]

     user_id  age
7601  U08786    7
8150  U08640    0
8318  U08752  250
8626  U08577  250
8797  U07956  250
8939  U08229    0

In [27]:
df.loc[
    (df["daily_screen_time_hours"] < 0) |
    (df["daily_screen_time_hours"] > 24),
    ["user_id", "daily_screen_time_hours"]
]

     user_id  daily_screen_time_hours
7766  U08624                    39.98
7786  U08138                    27.68
8098  U07509                    30.72
8187  U07511                    39.04
8330  U07615                    34.47
8409  U08741                    38.19
8467  U08726                    28.94
8670  U08162                    33.80

In [28]:
(df["daily_screen_time_hours"] > 24).sum()

np.int64(8)

In [29]:
df.loc[
    df["daily_screen_time_hours"] > 24,
    "daily_screen_time_hours"
] = np.nan

In [30]:
df["daily_screen_time_hours"].max()

23.39

In [31]:
df.loc[
    (df["sleep_hours"] < 0) |
    (df["sleep_hours"] > 24),
    ["user_id", "sleep_hours"]
]

Empty DataFrame
Columns: [user_id, sleep_hours]
Index: []

In [32]:
df.loc[
    (df["social_media_hours"] < 0) |
    (df["social_media_hours"] > 24),
    ["user_id", "social_media_hours"]
]

Empty DataFrame
Columns: [user_id, social_media_hours]
Index: []

In [33]:
df.loc[
    (df["gaming_hours"] < 0) |
    (df["gaming_hours"] > 24),
    ["user_id", "gaming_hours"]
]

Empty DataFrame
Columns: [user_id, gaming_hours]
Index: []

In [34]:
df.loc[
    (df["work_study_hours"] < 0) |
    (df["work_study_hours"] > 24),
    ["user_id", "work_study_hours"]
]

     user_id  work_study_hours
8641  U08686             24.76
8824  U07650             25.25
8918  U08527             25.02

In [35]:
df[[
    "notifications_per_day",
    "app_opens_per_day"
]].describe().T

,count,mean,std,min,25%,50%,75%,max
notifications_per_day,9015.0,138.643150,139.959323,20.0,76.5,136.0,191.0,4939.0
app_opens_per_day,9015.0,98.800776,74.786385,15.0,55.0,97.0,140.0,2986.0

In [36]:
df.isnull().sum()

transaction_id               0
user_id                      0
age                         19
gender                      10
daily_screen_time_hours     29
social_media_hours          13
gaming_hours                21
work_study_hours             7
sleep_hours                  9
notifications_per_day       15
app_opens_per_day           15
weekend_screen_time         18
stress_level                12
academic_work_impact        10
addiction_level            980
addicted_label               0
dtype: int64

In [37]:
(df.isnull().mean() * 100).round(2)

transaction_id              0.00
user_id                     0.00
age                         0.21
gender                      0.11
daily_screen_time_hours     0.32
social_media_hours          0.14
gaming_hours                0.23
work_study_hours            0.08
sleep_hours                 0.10
notifications_per_day       0.17
app_opens_per_day           0.17
weekend_screen_time         0.20
stress_level                0.13
academic_work_impact        0.11
addiction_level            10.85
addicted_label              0.00
dtype: float64

In [38]:
df["age"].isnull().sum()

np.int64(19)

In [39]:
(df["age"].isnull().mean() * 100).round(2)

np.float64(0.21)

In [40]:
df.isnull().sum()

transaction_id               0
user_id                      0
age                         19
gender                      10
daily_screen_time_hours     29
social_media_hours          13
gaming_hours                21
work_study_hours             7
sleep_hours                  9
notifications_per_day       15
app_opens_per_day           15
weekend_screen_time         18
stress_level                12
academic_work_impact        10
addiction_level            980
addicted_label               0
dtype: int64

In [41]:
missing = df.isnull().sum()
print(missing[missing > 0])

age                         19
gender                      10
daily_screen_time_hours     29
social_media_hours          13
gaming_hours                21
work_study_hours             7
sleep_hours                  9
notifications_per_day       15
app_opens_per_day           15
weekend_screen_time         18
stress_level                12
academic_work_impact        10
addiction_level            980
dtype: int64

In [42]:
numeric_cols = [
    "age",
    "daily_screen_time_hours",
    "social_media_hours",
    "gaming_hours",
    "work_study_hours",
    "sleep_hours",
    "notifications_per_day",
    "app_opens_per_day",
    "weekend_screen_time"
]

In [43]:
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [44]:
df["gender"].value_counts(dropna=False)

gender
Male       3041
Other      2985
Female     2965
NaN          10
OTHER         3
M             3
O             3
Mle           2
MALE          2
other         2
male          2
Femlae        2
Unknown       2
 Female       2
Others        1
female        1
FEMALE        1
f             1
F             1
m             1
Name: count, dtype: int64

In [47]:
df["gender"] = df["gender"].replace({
    "Femlae": "Female",
    "Mle": "Male",
    "F": "Female",
    "M": "Male"
})

In [46]:
df["gender"].value_counts(dropna=False)

gender
Male       3046
Other      2985
Female     2968
NaN          10
OTHER         3
O             3
MALE          2
other         2
Unknown       2
 Female       2
male          2
female        1
Others        1
FEMALE        1
f             1
m             1
Name: count, dtype: int64

In [48]:
df["gender"] = df["gender"].str.strip().str.title()
df["gender"] = df["gender"].replace({
    "M": "Male",
    "F": "Female",
    "O": "Other",
    "Others": "Other"
})

In [49]:
df["gender"] = df["gender"].fillna("Unknown")

In [50]:
df["gender"].value_counts(dropna=False)

gender
Male       3051
Other      2994
Female     2973
Unknown      12
Name: count, dtype: int64

In [51]:
df["stress_level"].value_counts(dropna=False)

stress_level
High       3060
Low        2978
Medium     2941
NaN          12
Unknown       5
H             4
Med           4
LOW           4
Hgh           4
L             3
Low           3
low           3
med           3
HIGH          2
Medium        1
high          1
medium        1
MEDIUM        1
Name: count, dtype: int64

In [53]:
df["stress_level"].value_counts(dropna=False)
df["stress_level"] = (
    df["stress_level"]
    .astype("string")
    .str.strip()
    .str.title()
)

In [54]:
df["stress_level"] = df["stress_level"].replace({
    "Hgh": "High",
    "Mod": "Medium",
    "Med": "Medium",
    "Lw": "Low"
})

In [55]:
df["stress_level"].value_counts(dropna=False)

stress_level
High       3067
Low        2988
Medium     2951
<NA>         12
Unknown       5
H             4
L             3
Name: count, dtype: Int64

In [56]:
df["stress_level"] = df["stress_level"].replace({
    "H": "High",
    "L": "Low"
})

In [57]:
df["stress_level"].value_counts(dropna=False)

stress_level
High       3071
Low        2991
Medium     2951
<NA>         12
Unknown       5
Name: count, dtype: Int64

In [58]:
df["academic_work_impact"].value_counts(dropna=False)

academic_work_impact
Yes        4529
No         4461
NaN          10
N             4
y             4
NO            3
no            3
0             3
1             3
False         3
YES           2
n             1
Unknown       1
yes           1
Y             1
True          1
Name: count, dtype: int64

In [59]:
df["academic_work_impact"] = (
    df["academic_work_impact"]
    .astype("string")
    .str.strip()
    .str.title()
)

In [60]:
df["academic_work_impact"].value_counts(dropna=False)

academic_work_impact
Yes        4532
No         4467
<NA>         10
N             5
Y             5
0             3
False         3
1             3
Unknown       1
True          1
Name: count, dtype: Int64

In [61]:
df["academic_work_impact"] = df["academic_work_impact"].replace({
    "Y": "Yes",
    "N": "No",
    "True": "Yes",
    "False": "No",
    "1": "Yes",
    "0": "No"
})

In [62]:
df["academic_work_impact"].value_counts(dropna=False)

academic_work_impact
Yes        4541
No         4478
<NA>         10
Unknown       1
Name: count, dtype: Int64

In [63]:
df["addiction_level"].value_counts(dropna=False)

addiction_level
Moderate        3465
Severe          2909
Mild            1646
NaN              980
Mod                4
Moderate           4
MILD               3
SEVERE             3
moderate           3
MODERATE           2
Sever              2
Svr                2
No addiction       2
mild               1
Mld                1
Unknown            1
severe             1
NONE               1
Name: count, dtype: int64

In [65]:
df["addiction_level"] = (
    df["addiction_level"]
    .astype("string")
    .str.strip()
    .str.title()
)
df["addiction_level"] = df["addiction_level"].replace({
    "Mod": "Moderate",
    "Mld": "Mild",
    "Sever": "Severe",
    "Svr": "Severe"
})
df["addiction_level"].value_counts(dropna=False)

addiction_level
Moderate        3478
Severe          2917
Mild            1651
<NA>             980
No Addiction       2
Unknown            1
None               1
Name: count, dtype: Int64

In [67]:
df["addiction_level"] = (
    df["addiction_level"]
    .astype("string")
    .str.strip()
    .str.title()
)
df["addiction_level"] = df["addiction_level"].replace({
    "Mod": "Moderate",
    "Mld": "Mild",
    "Sever": "Severe",
    "Svr": "Severe"
})
df["addiction_level"].value_counts(dropna=False)

addiction_level
Moderate        3478
Severe          2917
Mild            1651
<NA>             980
No Addiction       2
Unknown            1
None               1
Name: count, dtype: Int64

In [68]:
df["addicted_label"].value_counts(dropna=False)

addicted_label
1       6379
0       2624
yes        6
-1         5
True       5
No         4
Yes        3
2          2
9          2
Name: count, dtype: int64

In [69]:
df["addicted_label"].unique()

array(['0', '1', 'Yes', '-1', 'yes', 'True', '2', 'No', '9'], dtype=object)

In [70]:
df.groupby("addicted_label")["addiction_level"].value_counts(dropna=False)

addicted_label  addiction_level
-1              Severe                3
                Mild                  1
                <NA>                  1
0               Mild               1646
                <NA>                972
                Severe                4
                No Addiction          1
                None                  1
1               Moderate           3468
                Severe             2904
                <NA>                  6
                Unknown               1
2               Mild                  2
9               Moderate              1
                Severe                1
No              Moderate              2
                Severe                2
True            Moderate              2
                Mild                  1
                No Addiction          1
                Severe                1
Yes             Moderate              3
yes             Moderate              2
                Severe                2
                Mild                  1
                <NA>                  1
Name: count, dtype: int64

In [71]:
df["addicted_label"] = (
    df["addicted_label"]
    .astype("string")
    .str.strip()
    .str.lower()
)

df["addicted_label"] = df["addicted_label"].replace({
    "yes": "1",
    "true": "1",
    "no": "0"
})

df["addicted_label"].value_counts(dropna=False)

addicted_label
1     6393
0     2628
-1       5
2        2
9        2
Name: count, dtype: Int64

In [72]:
df[df["addicted_label"].isin(["-1", "2", "9"])][
    ["user_id", "addiction_level", "addicted_label"]
]

     user_id addiction_level addicted_label
7611  U08101          Severe             -1
7644  U08675          Severe             -1
7971  U08393            Mild              2
8199  U08646            <NA>             -1
8379  U07913            Mild              2
8444  U08409          Severe              9
8590  U08447        Moderate              9
8646  U08707            Mild             -1
8861  U07936          Severe             -1

In [73]:
df["addicted_label"] = df["addicted_label"].replace(
    ["-1", "2", "9"], pd.NA
)

df["addicted_label"].value_counts(dropna=False)

addicted_label
1       6393
0       2628
<NA>       9
Name: count, dtype: Int64

In [74]:
df.duplicated().sum()

np.int64(160)

In [75]:
df[df.duplicated(keep=False)].head(10)

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
56,TXN00057,U00057,35,Male,5.63,5.69,2.55,4.64,4.96,23.0,161.0,6.84,Medium,No,Severe,1
101,TXN00102,U00102,27,Female,5.95,0.54,2.99,1.47,6.21,200.0,73.0,7.70,High,No,<NA>,0
140,TXN00141,U00141,29,Male,7.63,1.08,0.97,1.17,6.52,56.0,39.0,8.26,Medium,No,Mild,0
183,TXN00184,U00184,25,Other,5.70,5.05,0.32,5.95,7.42,28.0,38.0,7.21,Medium,No,Moderate,1
275,TXN00276,U00276,24,Other,7.20,4.22,3.30,2.68,4.96,150.0,110.0,9.10,High,No,Severe,1
402,TXN00403,U00403,23,Male,11.89,3.89,3.96,2.93,5.16,31.0,74.0,12.89,Medium,Yes,Moderate,1
412,TXN00413,U00413,22,Male,9.54,4.71,3.52,2.78,6.35,133.0,178.0,12.37,Medium,Yes,Moderate,1
459,TXN00460,U00460,20,Other,4.14,0.92,3.14,1.89,7.27,90.0,80.0,4.68,Low,Yes,<NA>,0
500,TXN00501,U00501,20,Female,3.20,4.91,3.34,3.36,6.01,168.0,102.0,5.34,Medium,No,Severe,1
701,TXN00702,U00702,21,Female,5.62,1.11,1.36,3.76,5.35,49.0,161.0,7.04,Medium,No,<NA>,0

In [76]:
df = df.drop_duplicates()

In [77]:
df.shape

(8870, 16)

In [78]:
df.isnull().sum()

transaction_id               0
user_id                      0
age                          0
gender                       0
daily_screen_time_hours      0
social_media_hours           0
gaming_hours                 0
work_study_hours             0
sleep_hours                  0
notifications_per_day        0
app_opens_per_day            0
weekend_screen_time          0
stress_level                12
academic_work_impact        10
addiction_level            965
addicted_label               9
dtype: int64

In [79]:
df["stress_level"] = df["stress_level"].fillna("Unknown")

df["academic_work_impact"] = (
    df["academic_work_impact"].fillna("Unknown")
)

In [80]:
df[["stress_level", "academic_work_impact"]].isnull().sum()

stress_level            0
academic_work_impact    0
dtype: int64

In [81]:
df[[
    "age",
    "daily_screen_time_hours",
    "social_media_hours",
    "gaming_hours",
    "work_study_hours",
    "sleep_hours",
    "notifications_per_day",
    "app_opens_per_day",
    "weekend_screen_time"
]].describe()

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time
count,8870.0,8870.000000,8870.000000,8870.000000,8870.000000,8870.000000,8870.000000,8870.000000,8870.000000
mean,26.651071,7.548011,3.281679,2.031525,3.263715,6.748206,137.818602,98.602593,9.299537
std,6.642346,2.665504,1.615059,1.181518,1.694926,1.333739,127.189747,71.326519,2.906467
min,0.0,2.640000,0.500000,0.000000,0.500000,0.000000,20.000000,15.000000,3.580000
25%,22.0,5.270000,1.910000,1.030000,1.860000,5.630000,77.000000,56.000000,7.000000
50%,27.0,7.560000,3.270000,2.050000,3.250000,6.740000,135.000000,97.000000,9.290000
75%,31.0,9.840000,4.640000,3.000000,4.650000,7.850000,191.000000,140.000000,11.547500
max,250.0,23.390000,15.420000,13.400000,25.250000,20.000000,4939.000000,2986.000000,47.900000

In [82]:
df[
    (df["age"] < 13) |
    (df["age"] > 100) |
    (df["work_study_hours"] > 24)
][[
    "user_id",
    "age",
    "work_study_hours",
    "daily_screen_time_hours",
    "sleep_hours"
]]

     user_id  age  work_study_hours  daily_screen_time_hours  sleep_hours
7601  U08786    7              2.52                     3.32         8.53
8150  U08640    0              5.61                     8.96         6.51
8318  U08752  250              4.26                     7.18         7.54
8626  U08577  250              5.65                     6.72         6.69
8641  U08686   28             24.76                     3.79         7.17
8797  U07956  250              3.55                     9.11         7.79
8824  U07650   24             25.25                     6.10         7.33
8918  U08527   27             25.02                     4.45         5.61
8939  U08229    0              1.83                     5.86         5.37

In [83]:
df.loc[df["age"] < 13, "age"] = np.nan
df.loc[df["age"] > 100, "age"] = np.nan

df.loc[df["work_study_hours"] > 24, "work_study_hours"] = np.nan

In [84]:
df[["age", "work_study_hours"]].describe()

             age  work_study_hours
count     8864.0       8867.000000
mean   26.583709          3.256357
std     5.201631          1.647320
min         18.0          0.500000
25%         22.0          1.860000
50%         27.0          3.250000
75%         31.0          4.650000
max         35.0         23.370000

In [85]:
df[[
    "daily_screen_time_hours",
    "social_media_hours",
    "gaming_hours",
    "sleep_hours",
    "weekend_screen_time"
]].describe()

,daily_screen_time_hours,social_media_hours,gaming_hours,sleep_hours,weekend_screen_time
count,8870.000000,8870.000000,8870.000000,8870.000000,8870.000000
mean,7.548011,3.281679,2.031525,6.748206,9.299537
std,2.665504,1.615059,1.181518,1.333739,2.906467
min,2.640000,0.500000,0.000000,0.000000,3.580000
25%,5.270000,1.910000,1.030000,5.630000,7.000000
50%,7.560000,3.270000,2.050000,6.740000,9.290000
75%,9.840000,4.640000,3.000000,7.850000,11.547500
max,23.390000,15.420000,13.400000,20.000000,47.900000

In [86]:
df[df["weekend_screen_time"] > 24][
    ["user_id", "daily_screen_time_hours", "weekend_screen_time"]
]

     user_id  daily_screen_time_hours  weekend_screen_time
7564  U08483                    10.96                42.01
7565  U08572                     7.58                47.15
7736  U08488                     7.56                46.80
7737  U08074                     4.20                33.11
7774  U08343                     4.85                25.07
7823  U08375                     7.55                40.88
7949  U07824                     7.43                43.13
8170  U07786                     7.10                47.07
8659  U08419                     8.98                47.90

In [87]:
df.loc[
    df["weekend_screen_time"] > 24,
    "weekend_screen_time"
] = np.nan

In [88]:
df["weekend_screen_time"].isnull().sum()

np.int64(9)

In [89]:
df[
    (df["social_media_hours"] > 24) |
    (df["gaming_hours"] > 24) |
    (df["sleep_hours"] > 24)
][[
    "user_id",
    "social_media_hours",
    "gaming_hours",
    "sleep_hours"
]]

Empty DataFrame
Columns: [user_id, social_media_hours, gaming_hours, sleep_hours]
Index: []

In [90]:
df.isnull().sum()

transaction_id               0
user_id                      0
age                          6
gender                       0
daily_screen_time_hours      0
social_media_hours           0
gaming_hours                 0
work_study_hours             3
sleep_hours                  0
notifications_per_day        0
app_opens_per_day            0
weekend_screen_time          9
stress_level                 0
academic_work_impact         0
addiction_level            965
addicted_label               9
dtype: int64

In [91]:
numeric_cols = [
    "age",
    "work_study_hours",
    "weekend_screen_time"
]

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [92]:
df[numeric_cols].isnull().sum()

age                    0
work_study_hours       0
weekend_screen_time    0
dtype: int64

In [93]:
for col in [
    "gender",
    "stress_level",
    "academic_work_impact",
    "addiction_level"
]:
    print(f"\n{col}:")
    print(df[col].value_counts(dropna=False))

gender:
gender
Male       2995
Other      2936
Female     2927
Unknown      12
Name: count, dtype: int64

stress_level:
stress_level
High       3017
Low        2939
Medium     2897
Unknown      17
Name: count, dtype: Int64

academic_work_impact:
academic_work_impact
Yes        4456
No         4403
Unknown      11
Name: count, dtype: Int64

addiction_level:
addiction_level
Moderate        3411
Severe          2866
Mild            1624
<NA>             965
No Addiction       2
Unknown            1
None               1
Name: count, dtype: Int64

In [94]:
df["addiction_level"] = df["addiction_level"].replace({
    "None": "No Addiction"
})

In [95]:
df["addiction_level"].value_counts(dropna=False)

addiction_level
Moderate        3411
Severe          2866
Mild            1624
<NA>             965
No Addiction       3
Unknown            1
Name: count, dtype: Int64

In [96]:
print("Dataset shape:", df.shape)
print("\nDuplicate rows:", df.duplicated().sum())
print("\nMissing values:")
print(df.isnull().sum())

Dataset shape: (8870, 16)

Duplicate rows: 0

Missing values:
transaction_id               0
user_id                      0
age                          0
gender                       0
daily_screen_time_hours      0
social_media_hours           0
gaming_hours                 0
work_study_hours             0
sleep_hours                  0
notifications_per_day        0
app_opens_per_day            0
weekend_screen_time          0
stress_level                 0
academic_work_impact         0
addiction_level            965
addicted_label               9
dtype: int64

In [97]:
df.to_csv("Smartphone_Usage_Cleaned.csv", index=False)

In [103]:
from google.colab import files
files.download("Smartphone_Usage_Cleaned.csv")

In [104]:
check_df = pd.read_csv("Smartphone_Usage_Cleaned.csv")

print("Saved dataset shape:", check_df.shape)
print("Duplicate rows:", check_df.duplicated().sum())

Saved dataset shape: (8870, 16)
Duplicate rows: 0

In [100]:
pd.crosstab(
    df["addiction_level"],
    df["addicted_label"],
    dropna=False
)

addicted_label      0     1  <NA>
addiction_level
Mild             1619     2     3
Moderate            2  3408     1
No Addiction        2     1     0
Severe              6  2856     4
Unknown             0     1     0
<NA>              957     7     1

In [101]:

df["addicted_label"].value_counts(dropna=False)

addicted_label
1       6275
0       2586
<NA>       9
Name: count, dtype: Int64

In [102]:

print("Dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Dataset shape: (8870, 16)

Missing values:
transaction_id               0
user_id                      0
age                          0
gender                       0
daily_screen_time_hours      0
social_media_hours           0
gaming_hours                 0
work_study_hours             0
sleep_hours                  0
notifications_per_day        0
app_opens_per_day            0
weekend_screen_time          0
stress_level                 0
academic_work_impact         0
addiction_level            965
addicted_label               9
dtype: int64

Duplicate rows: 0

### Issue with Addiction Labels

While cleaning the dataset, I found that two columns, `addiction_level` and `addicted_label`, have missing values. There are 965 missing values in `addiction_level` and 9 missing values in `addicted_label`.

I also checked both columns together and found that some values are not matching properly. So, I did not fill these missing values by guessing or using the other column.

For now, I kept both columns in the cleaned dataset because we have not finalized which column will be used for addiction prediction. During the modelling stage, we can decide how to handle these missing values and check the inconsistent labels before training the model.